#cloud-config
hostname: <your hostname>
password: <your secure password>
chpasswd: {expire: False}
ssh_pwauth: true
ssh_authorized_keys:
  - <your id_rsa.pub key>
package_upgrade: true
packages:
- dhcp
#
bootcmd:
  - ifdown eth1
  - ifup eth1
runcmd:
  - 'echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/ip_forward.conf'
  - 'sysctl -p /etc/sysctl.d/ip_forward.conf'
  - 'setenforce 0'
  - 'firewall-cmd --change-interface=eth1 --zone=internal --permanent'
  - 'firewall-cmd --set-default-zone=external'
  - 'firewall-cmd --zone=internal --permanent --add-service https'
  - 'firewall-cmd --zone=internal --permanent --add-service ntp'
  - 'firewall-cmd --zone=internal --permanent --add-port=2426/udp'
  - 'firewall-cmd --zone=external --permanent --add-port=2426/udp'
  - 'firewall-cmd --zone external --permanent --add-masquerade'
  - 'firewall-cmd --zone external --permanent --add-forward-port=port=2426:proto=udp:toaddr=192.168.254.10'
  - 'firewall-cmd --complete-reload'
  - 'echo "default-lease-time 600;" > /etc/dhcp/dhcpd.conf'
  - 'echo "max-lease-time 7200;" >> /etc/dhcp/dhcpd.conf'
  - 'echo "subnet 192.168.254.0 netmask 255.255.255.0 {" >> /etc/dhcp/dhcpd.conf'
  - 'echo "   option subnet-mask 255.255.255.0;" >> /etc/dhcp/dhcpd.conf'
  - 'echo "   option routers 192.168.254.1;" >> /etc/dhcp/dhcpd.conf'
  - 'echo "   range 192.168.254.10 192.168.254.10;" >> /etc/dhcp/dhcpd.conf'
  - 'echo "}" >> /etc/dhcp/dhcpd.conf'
  - 'echo "nameserver 8.8.8.8" >> /ect/resolv.conf'
  - 'sed -i "s@ExecStart.*@ExecStart=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid eth1 @" /usr/lib/systemd/system/dhcpd.service'
  - 'echo "BOOTPROTO=static" > /etc/sysconfig/network-scripts/ifcfg-eth1'
  - 'echo "ONBOOT=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  - 'echo "DEVICE=eth1" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  - 'echo "IPADDR=\"192.168.254.1\"" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  - 'echo "NETMASK=\"255.255.255.0\"" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  - 'echo "DNS1=\"8.8.8.8\"" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  - 'echo "ZONE=external" >> /etc/sysconfig/network-scripts/ifcfg-eth0'
  - 'systemctl enable dhcpd'

final_message: "==== Cloud-init completed ===="
power_state:
 delay: "+1"
 mode: reboot
 message: Bye Bye
 timeout: 15
 condition: True
